calibration:
  length_offsets:
    l02: 0.0
    l24: 0.0
    l46: 0.0
    l6E: 0.0
    
  joint_offsets: 
    joint_1: 0.0
    joint_2: 0.0
    joint_3: 0.0
    joint_4: 0.0
    joint_5: 0.0
    joint_6: 0.0
    joint_7: 0.0